Regular expression
cpp-code/doeach-dw pull request #4
Opened 2019-12-26 02:17 UTC by doeach-dw

Resolve #1

Signed-off-by: doeach-dw <doeach@qq.com>

2019-12-26 04:33 UTC, dark-w requested changes

2019-12-26 04:33 UTC, dark-w commented on Makefile
> +	g++ $^ -o $@ $(LDFLAGS)
LDFLAGS? 定义在哪呢

2019-12-26 04:33 UTC, dark-w commented on Makefile
> +	@rm -vf *.o Re_expression
你上面的写法的话，需要删*.o吗

2019-12-26 04:33 UTC, dark-w commented on Re_expression.cc
> +    {
coding style

2019-12-26 04:33 UTC, dark-w commented on Re_expression.cc
> +        cout << "fail:" << endl;
括号不能省

2019-12-26 08:02 UTC, doeach-dw commented on Makefile
> +	g++ $^ -o $@ $(LDFLAGS)
是的 ，我没有double check

2019-12-26 11:27 UTC, dark-w requested changes
分支名全小写，下次注意

2019-12-26 11:27 UTC, dark-w commented on Re_expression.cc
> +    if(a)
再次认真看一下linux kernel coding style, if else for...括号的写法

2019-12-26 11:27 UTC, dark-w commented on Re_expression.cc
> +        for(int i; i <= 3; i++)
i建议显式初始化

2019-12-26 11:27 UTC, dark-w commented on Re_expression.cc
> +        for(int i; i <= 3; i++)
变量在使用前，记得init

2019-12-26 11:27 UTC, dark-w commented on Re_expression.cc
> +        cout << "fail:" << endl;
这条打印信息很让人疑惑，是还有信息没有显示完全吗？

2019-12-26 11:27 UTC, dark-w commented on configure
> +#!/bin/bash
这里暂时虽然没用到，但是建议写成更好的方式

2019-12-26 14:06 UTC, dark-w requested changes

2019-12-26 14:06 UTC, dark-w commented on Re_expression.cc
> +    {
不清楚"{"应该在哪个地方吗？应该与if else for ...同行的。

2019-12-26 14:06 UTC, dark-w commented on configure
> +#!/bin/bash
这里为什么不修改呢？是不知道怎么改吗

2019-12-27 02:05 UTC, doeach-dw commented on Re_expression.cc
> +        cout << "fail:" << endl;
是else下面没有跟for下面的对应匹配吗？

2019-12-27 02:05 UTC, doeach-dw commented on Re_expression.cc
> +    if(a)
这个是c++ 鸭

2019-12-27 02:05 UTC, doeach-dw commented on configure
> +#!/bin/bash
是的，这里我还不知道怎么修改

2019-12-27 02:05 UTC, doeach-dw commented on Re_expression.cc
> +    {
这里是c++，所以不用linux kernel coding style吧

2019-12-27 02:10 UTC, dark-w requested changes

2019-12-27 02:10 UTC, dark-w commented on Re_expression.cc
> +    {
C++? C++ "{"更应该在if同行，而且函数也要在同行了。

2019-12-27 02:10 UTC, dark-w commented on Re_expression.cc
> +{
你提醒我了，这个也要改。

2019-12-27 02:10 UTC, dark-w commented on configure
> +#!/bin/bash
知道env吗？去跑一下这个命令，man了解一下。

2019-12-27 02:32 UTC, doeach-dw commented on configure
> +#!/bin/bash
env 在修改的环境中运行程序，我知道了.

2019-12-27 02:32 UTC, doeach-dw commented on Re_expression.cc
> +{
好的

2019-12-27 02:45 UTC, dark-w requested changes

2019-12-27 02:45 UTC, dark-w commented on Re_expression.cc
> +int main(){
还是coding style，if while for 等关键字后面要加空格，()和{之间也需要一个空格。

2019-12-27 03:01 UTC, dark-w approved these changes

2019-12-27 03:01 UTC, merged